name = "cones"
uuid = "1968a8cd-39ef-403d-8c92-f9ddb7524d92"
authors = ["hervasa2 <hervasa2@live.unc.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
